spring:
  application:
    name: wifey

  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  web:
    resources:
      add-mappings: false

  security:
    user:
      name: ${BASICAUTH_USER}
      password: ${BASICAUTH_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: ${PORT:8001}
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
      - text/html
      - text/plain
      -
content:
  recipe: "content/recipe"

jwt:
  secret: ${JWT_SECRET}

logging:
  include-application-name: false
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.springframework.security.web.FilterChainProxy: ERROR

