spring:
  application:
    name: wifey
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      add-mappings: false
  http:
    log-request-details=true:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null

ai:
  url: ""
  method: ""

content:
  recipe: "content/recipe"

logging:
  include-application-name: false
  level:
    org.springframework.security.web.util.matcher: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.web.servlet.DispatcherServlet: TRACE
    org.springframework.web.servlet.handler.AbstractHandlerMapping: TRACE
