spring:
  application:
    name: wifey

  datasource:
    url: jdbc:mysql://localhost:3306/project_wifey
    username: projectuser
    password: root123
  jpa:
    hibernate:
      ddl-auto: update

server:
  address: 192.168.0.199
  port: 8001
