rootLogger.name=Root
rootLogger.level=INFO
rootLogger.appenderRef.1.ref=ConsoleAppender

logger.0.name=com.zio.util.AspectLogging
logger.0.level=TRACE
logger.0.appenderRef.2.ref=TracerAppender

logger.1.name=com.zio.util.AspectExceptions
logger.1.level=ERROR
logger.1.appenderRef.3.ref=ErrorAppender

appender.1.name=ConsoleAppender
appender.1.type=Console
appender.1.layout.type=PatternLayout
appender.1.layout.patter=%p %c %t -%m%n

#file appender
appender.3.name=ErrorAppender
appender.3.type=File
appender.3.fileName=logs/user/ErrorLog.log

#file appender
appender.2.name=TracerAppender
appender.2.type=File
appender.2.fileName=logs/user/TraceLog.log



